const automationProjects = [
  {
    id: 'ai-whatsapp-guesthouse',
    title: 'AI WhatsApp Guest House Agent',
    img: '/automation/guesthouse-agent.png',
    link: '/automation/ai-whatsapp-guesthouse',
    date: '2025',
    category: 'Hospitality Automation',
    company: 'AI Automation',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/automation/guesthouse-agent.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/automation/guesthouse-bookingagent.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/automation/guesthouse-photo.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/automation/guesthouse-owner.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/automation/guesthouse-agents.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'AI WhatsApp Guest House Agent — An advanced AI-powered WhatsApp agent designed for guest houses, capable of managing the entire booking lifecycle.',
      'Key Highlights:',
      '• Orchestrates over six specialized AI agents that collaborate seamlessly',
      '• Handles reservations, share property details, sync calendars',
      '• Direct interaction with both guests and the owner',
      '• End-to-end guest house management through WhatsApp',
      '• Automated booking confirmations and real-time calendar sync',
      '• Instant photo and info sharing capabilities',
      '• Direct owner communication handled by AI agents',
    ],
    tools: [
      'n8n',
      'OpenAI GPT',
      'WhatsApp API',
      'Google Calendar',
      'Embeddings (OpenAI)',
      'Vector Knowledge Base',
      'Custom Sub-Workflows',
    ],
    results:
      'End-to-end guest house management through WhatsApp: automated booking confirmations, real-time calendar sync, instant photo and info sharing, and direct owner communication — all handled by AI agents working together.',
    complexity: 'Expert',
    featured: true,
  },
  {
    id: 'ai-price-tracker',
    title: 'AI-Powered Competitor Price Tracker',
    img: '/automation/price-tracker.png',
    link: '/automation/ai-price-tracker',
    date: '2025',
    category: 'E-commerce Automation',
    company: 'E-commerce Solutions',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/automation/price-tracker.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'AI-Powered Competitor Price Tracker — Automated competitor price monitoring system built with n8n workflows, advanced scraping methods, and LLM-powered data analysis.',
      'Key Highlights:',
      '• Real-time dashboards with instant alerts',
      '• Scalable multi-source monitoring without manual intervention',
      '• Advanced scraping methods with LLM-powered analysis',
      '• Integration with Google Sheets and Looker Studio',
      '• Instant Slack alerts for price changes',
      '• Automated dashboards with zero manual effort',
    ],
    tools: [
      'n8n',
      'Scraperfly',
      'Google Gemini 2.5',
      'OpenAI API',
      'Google Sheets',
      'Looker Studio',
      'Slack',
    ],
    results:
      'Real-time competitor pricing insights with instant Slack alerts, automated dashboards, and zero manual effort.',
    complexity: 'Advanced',
    featured: true,
  },
  {
    id: 'ai-cold-email-automation',
    title: 'AI-Powered Multi-Step Cold Email Automation',
    img: '/automation/cold-email.png',
    link: '/automation/ai-cold-email-automation',
    date: '2025',
    category: 'Sales Automation',
    company: 'Sales Tech',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/automation/cold-email.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'AI-Powered Multi-Step Cold Email Automation — Fully automated outreach system that generates personalized 4-step email sequences for decision-makers.',
      'Key Highlights:',
      '• Company data analysis to identify opportunities and weaknesses',
      '• Crafts highly targeted messages that stand out from generic outreach',
      '• Automated 4-step email sequences for decision-makers',
      '• Personalized content generation using AI',
      '• Scalable for unlimited leads with zero manual effort',
      '• Integration with Google Sheets for lead management',
    ],
    tools: [
      'n8n',
      'ChatGPT API',
      'Google Sheets',
      'Email Copywriting',
      'Cold Email Automation',
      'AI Data Analytics',
    ],
    results:
      'End-to-end automated cold outreach with personalized sequences, scalable for unlimited leads.',
    complexity: 'Advanced',
    featured: true,
  },
  {
    id: 'ai-lead-qualification',
    title: 'AI-Powered Lead Qualification & Service Recommendation System',
    img: '/automation/lead-qualification.png',
    link: '/automation/ai-lead-qualification',
    date: '2025',
    category: 'Marketing Automation',
    company: 'Marketing Tech',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/automation/lead-qualification.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'AI-Powered Lead Qualification & Service Recommendation System — Intelligent automation that evaluates filtered leads and recommends the most relevant services.',
      'Key Highlights:',
      '• Uses Perplexity AI for data enrichment and analysis',
      '• Custom JavaScript for advanced logic processing',
      '• Google Sheets integration for reporting and tracking',
      '• Classifies prospects into service categories automatically',
      '• Web Development, Social Media Management, Video Editing classification',
      '• Reduces manual research and increases outreach precision',
    ],
    tools: [
      'n8n',
      'Perplexity AI',
      'Google Sheets',
      'JavaScript',
      'API Integration',
    ],
    results:
      'Automated classification of leads into service categories, reducing manual research and increasing outreach precision.',
    complexity: 'Advanced',
    featured: true,
  },
  {
    id: 'ai-lead-social-automation',
    title: 'AI-Powered Lead Qualification & Social Media Activity Automation',
    img: '/automation/lead-social-automation.png',
    link: '/automation/ai-lead-social-automation',
    date: '2025',
    category: 'Sales Automation',
    company: 'Social Analytics',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/automation/lead-social-automation.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'AI-Powered Lead Qualification & Social Media Activity Automation — End-to-end automation that enriches company data and evaluates digital presence across multiple platforms.',
      'Key Highlights:',
      '• Collects company details from multiple data sources',
      '• Identifies exact social media accounts automatically',
      '• Checks recent activity and analyzes posting consistency',
      '• Qualifies high-potential leads based on digital engagement',
      '• Integrates with Apify for advanced data scraping',
      '• Saves hours of manual research with automated workflows',
    ],
    tools: [
      'n8n',
      'Apify',
      'Google Sheets',
      'ChatGPT API',
      'JavaScript',
      'AI Data Analytics',
    ],
    results:
      'Saved hours of manual research by automating social media checks and ensuring only engaged, high-potential leads enter the sales pipeline.',
    complexity: 'Advanced',
    featured: true,
  },
];

export default automationProjects;
