const projects = [
  {
    id: 'pinarea-website',
    title: 'Pinarea Guest House',
    img: '/project3/project3.webp',
    link: '/projects/pinarea-website',
    date: '2025',
    liveLink: 'https://guesthouse-booking-five.vercel.app/',
    company: 'Pinarea',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/project3/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Guest House Booking System — A modern, full-stack booking platform built with Next.js, Prisma, and Clerk authentication, enhanced with AI assistance and a 360° interactive property view.',
      'Key Highlights:',
      '• Interactive calendar showing real-time availability',
      '• Booking request form with validation',
      '• Responsive design for mobile and desktop',
      '• Real-time availability checking',
      '• AI-powered assistant to handle guest queries and automate support',
      '• 360° immersive guest house view for interactive exploration',
      '• Secure admin authentication with Clerk',
      '• Dashboard with detailed booking statistics',
      '• Approve or reject booking requests',
      '• Block dates for maintenance and special events',
      '• Centralized booking and calendar management with real-time updates',
    ],
  },
  {
    id: 'navix-agency',
    title: 'Navix Agency',
    img: '/project4/project4.png',
    link: '/projects/navix-agency',
    date: '2024',
    company: 'Navix',
    liveLink: 'https://www.navixagency.tech/en',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/project4/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project4/1.webm',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project4/2.webm',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project4/4.png',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project4/5.png',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project4/3.png',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project4/6.png',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project4/9.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.png',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'NAVIX — A cutting-edge AI-powered platform that redefines how agencies present, interact, and convert leads in 2025 and beyond.',
      'Key Highlights:',
      '• Real-time conversational assistant for service navigation',
      '• Full speech-to-text and text-to-speech voice interface',
      '• Smart project recommendations powered by vector search (Pinecone)',
      '• Seamless multilingual support (English, French, Arabic with RTL)',
      '• Real-time CMS editing via Sanity with AI-driven content syncing',
      '• Optimized for SEO, Lighthouse scores, and Core Web Vitals performance',
    ],
  },
  {
    id: 'house-protein',
    title: 'House Protein Bizerte',
    img: '/project5/project5.png',
    link: '/projects/house-protein',
    date: '2025',
    company: 'House Protein',
    liveLink: 'https://www.house-protein.tn/',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/project5/1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.png',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project5/4.png',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project5/5.png',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project5/6.png',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project5/7.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/10.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Nutrition Store E-Commerce — A high-performance e-commerce platform built for a Tunisian nutrition store using Next.js, Sanity, and Framer Motion.',
      'Key Highlights:',
      '• Fully optimized for SEO with structured data, meta tags, and image previews',
      '• Facebook Pixel integration for advanced tracking and analytics',
      '• Fast, scalable architecture designed to handle growth',
      '• Smooth, modern animations with Framer Motion',
      '• Content managed via Sanity for flexibility and easy updates',
    ],
  },
  {
    id: 'scrimify-ai',
    title: 'Scrimify AI',
    img: '/project1/project1.webp',
    link: '/projects/scrimify-ai',
    date: '2025',
    company: 'Sehatech',
    livelink: 'https://scrimify-ai.vercel.app/',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Scrimify — A modern esports team management platform designed to make matchmaking and roster coordination smarter and more efficient. Built with Next.js 15, TypeScript, and Supabase.',
      'Key Highlights:',
      '• Intelligent team compatibility assessment based on multiple strategic factors',
      '• Smart opponent discovery using over 15 performance and playstyle metrics',
      '• Real-time roster management and team coordination tools',
      '• League of Legends integration for match history and performance tracking',
      '• Fully responsive, modern interface using Tailwind CSS and Radix UI',
    ],
  },
  {
    id: 'benders',
    title: 'Benders',
    img: '/project6/project2.png',
    link: '/projects/benders',
    date: '2025',
    company: 'Mitutoyo',
    liveLink: 'https://www.shtc-maghreb.tn/',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/project6/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project6/1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project6/2.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project6/3.png',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project6/4.png',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Benders Agency Landing Page — A modern, high-performance website built to reflect bold vision, motion, and creativity. Developed with Next.js for speed and GSAP for smooth, scroll-based animations that enhance user engagement.',
      'Key Highlights:',
      '• Engaging GSAP animations delivering a dynamic scroll experience',
      '• SEO-optimized Next.js architecture with 90+ Lighthouse score',
      '• Fast, responsive design with a sleek and modern UI',
      '• Clean, scalable structure built for future content growth',
    ],
  },
  {
    id: 'houssem-consulting',
    title: 'Houssem Consulting',
    img: '/project2/project2.png',
    link: '/projects/houssem-consulting',
    date: '2025',
    company: 'Mitutoyo',
    liveLink: 'https://www.shtc-maghreb.tn/',
    primary: '#1a1a1a',
    accentColor: '#fefcfa',
    secondary: '#f5f5f5',
    fillColor: '#ff8c42',
    menuColor: '#ff6b35',
    menuFontColor: '#fefcfa',
    fluidColor: '#ff9966',
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.png',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/4.png',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project2/5.png',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Houssem Consulting x Mitutoyo — A tailored web-based solution built to digitize and streamline data collection, monitoring, and reporting for a global leader in industrial automation and precision quality control.',
      'Key Highlights:',
      '• Secure role-based authentication with NextAuth.js and JWT for data compliance',
      '• Custom data entry flows aligned with operational procedures',
      '• Real-time dashboards with Chart.js for trend analysis and actionable insights',
      '• MongoDB backend with robust API validation ensuring data integrity',
      '• CSV and Excel export for audit-ready reporting and reviews',
      '• Responsive, high-performance interface optimized for desktop and tablet use',
      '• Built with Next.js, React, TailwindCSS, and designed for scalability',
    ],
  },
];
export default projects;
